### ISSUE TITLE
Tooltips unexpected hide

### ISSUE THREAD

**Issue by morawcik** [zininzinin/AutoTrimps#106]
Hi.

When script not paused and I hover to some gui element like maps button tooltip blinked (open and hide in 0.01s (or sth like that).

**Comment by spindrjr** [comment]
This WAS caused by some limitations of the base game code. In the latest update the dev kindly added some features for me. I pushed the updated AutoTrimps code about 10 minutes before you posted this in which I would expect no tooltips to automatically close (except the new one you get when breaking the world).

**Comment by morawcik** [comment]
Thanks, now it's work :)
