### ISSUE TITLE
Lead would rather get stuck on an even numbered zone then run maps for prestiges

### ISSUE THREAD

**Issue by voidlily** [zininzinin/AutoTrimps#123]
I started a Lead run today and noticed AutoTrimps would get stuck on even numbered zones. I first noticed it on zone 34. It wanted to run maps for "needs more damage" but wouldn't run a map on even numbered zones. When I went to run a map manually there were a lot of prestiges available that AutoTrimps wasn't getting.

Would it make sense to run maps on even numbered zones if you need damage and there are prestiges available?

**Comment by spindrjr** [comment]
Getting stuck/wanting more damage that early on a lead run says to me that the prestige setting is wrong (or probably off). What is yours set at? I use megamace.

**Comment by voidlily** [comment]
Mine is off. I didn't realize I needed to have it set to something.

**Comment by voidlily** [comment]
I set it to megamace and next run I'll see if that fixes it.

**Comment by spindrjr** [comment]
This seems to be a point of confusion for some people. For my reference, did you not see the setting? Or did you see the setting and not understand it so left it off? Or did you know what it is and decided it was best left off?

**Comment by voidlily** [comment]
I didn't understand the setting at first so I left it off.

**Comment by spindrjr** [comment]
Yea it's sort of a core speed-climbing technique. Some of the difficulty changes in higher challenges can get caught up with no prestige setting on. I've changed it to default to Polierarm instead of Off and added some more explanation to the tooltip.

I am confident you will not get stuck at a low level like this again (and your he/hr will probably increase significantly) so I will close this for now. If you do have the same issue, feel free to re-open or submit a new one.
