### ISSUE TITLE
Add max warpstation please

### ISSUE THREAD

**Issue by Sciencefreak** [zininzinin/AutoTrimps#160]
I know that the amount of warpstations increase with each gigastation purchased and that there should be no hard cap like for huts, houses, hotels ...
But it is a waste of metal if you farm metal maps for 30min to upgrade your equipment but you buy a new warpstation instead. This warpstation increases your total population by maybe 0.2% compared to the maybe 30% attack increase a new prestige upgrade would give.

I would suggest a cap corresponding to the gigastation setting. 

0 would mean, that you buy exactly the amount you would buy before getting next giga and wait for next giga upgrade if not available. (take care with coding because it could be noninteger and you have to build at least as much warpstations as needed for next gigaupgrade)

10 means, that you are going to buy at most 10 more warp stations before stopping

-1 means that it works like now, hence infinite warpstations

Much more advanced setting (also more difficult to code) would be, to only buy warpstations if you have enough ressoures to get enough trimps to buy next coordination upgrade

**Comment by genbtc** [comment]
The code for this is already done and will try to commit soon

**Comment by Hider-The-First** [comment]
Hard cup
If you are planing to use X hard cup then you are saying you are willing to correct a Giga/Delta setting that you didn't set right by a max correction of X/N of your warps, from my experience, even high familiarity with the world of trimps may not stop you from doing a 30%+ mistakes.

30% attack from new prestige takes 30 min farming
If you are about to get a new prestige that you need 30 minutes to farm for then your last prestige is at level 10? then how will you get 30% of it? you are going to buy 3? its hypothetical assumption.

Conclusion
hypothetical a cap is a good idea assuming you set your Giga/Delta right
It will provide you a solutions to a problem that is fairly far from the one you are suggesting,
and since the problem it can solve is minor, then the solution should not be so radical as a 30% cut of your population.
You should talk to us in the Zininzinin chat, its fairly active
and try to be a bit Trigger-happy regarding to portals.
https://discord.gg/0VbWe0dxB9kIfV2C

**Comment by genbtc** [comment]
Implemented Warpstation Cap - if we are past the basewarp+deltagiga level, "hard cap" and just wait for next giga. f37a675a2d2197576bba937874766dff80035e8a
