### ISSUE TITLE
toggleAutoTrap()

### ISSUE THREAD

**Issue by andilem** [zininzinin/AutoTrimps#164]
toggleAutoTrap() is called somewhere, but this function doesn't seem to exist. The AutoTrapping feature doesn't work. The script just does Researching (lowest resource I think).

**Comment by genbtc** [comment]
The function is located in the main game, thats why you can't find it. This is the green/red button that says AutoTraps in the build bar.   This relates to building traps.

The script should "User" Trap trimps (actually trap them) only when you are so severely low on trimps that it needs to do so.  Otherwise it will research science or metal if you have a turkimp.

Please report back and state your underlying issue.

**Comment by andilem** [comment]
Thanks for the clarification.
I have the problem that the script keeps "Research"ing although it would be way better to "Check Traps" if I haven't got full trimps and to switch to "Build"ing if the trimp bar is full. I thought the script is supposed to do this, but obvously I was wrong.
This can be closed.

**Comment by genbtc** [comment]
look in the function manualLabor() to determine what the actions it takes are. 
setGather('trimps'); means actively trap trimps, and this happens in two places. 
1)If you are down to Less than 5 trimps and you have traps already built.
2)If you have Autotrimps' Autotrapping setting turned on and the remaining breed time (getBreedTime(true)) is greater than the Autotrimps' Breed Timer setting is set to. (getPageSetting('GeneticistTimer'))

Hope this helps.
