### ISSUE TITLE
Bug: abandoning when genetecist timer is above 30.

### ISSUE THREAD

**Issue by tigesso** [zininzinin/AutoTrimps#193]
Hi!
Today I spotted an issue. Yesterday everything was OK, today problem occured. its my settings: http://scr.hu/9ghf/dm2yz While farming maps (repeat on, repeat forever) everything is fine as long as I have some dead trimps. When I got full trimps then autotrimps instantly abandon map. Reentering map couse new breeding so i can farm 31s more and script abandon map again.

Searching when exacly problem occured I found that two things must be:
When I enter map not having max trimps.
AND "Geneticist Timer" is higher than 30s. (not including infinite)

Is that me or anybody has same problem?

**Comment by genbtc** [comment]
you should Set your breed timer to 30 not 31. That is why.  Its trying to get your anticipation stacks to match your breed timer, but obviously since 30 is the max anti stacks, it tries to abandon (force kill you) to reach 31 but it can't.  Look at Line 2044-2055 in the script if you can read code. I will look into fixing it, so that 30 is the cap for that section (your timer setting should be not higher than 30, but I can try to include some protection from that).  

I realize now why you wanted 31, because 30 would do something like "29.6" and result in 29 anti stacks. This has since been fixed as of the same time yesterday when I made the other changes. Now 30 should be more accurate, and really mean 30.

**Comment by genbtc** [comment]
This should now be fixed in the gen BTC branch: https://github.com/zininzinin/AutoTrimps/issues/208
