### ISSUE TITLE
5 Suggestions for Improving Autotrimps

### ISSUE THREAD

**Issue by Day-Elven** [zininzinin/AutoTrimps#205]
Autotrimps helps all of a lot, and they can help even more. I have several suggestions how to improve them.

1. Autocompleting daily challenges. Daily challenges are good for those who can reach high zones (because currently the best He challenged is limited by z190), also they are required for achievements (and damage bonus is one of the most important things in this game). For example: IF daily challenge option is active AND there is available daily challenge, THEN instead of normal challenge daily challenge will be selected in the next run in He/Hr mode.
2. MAPS
2.0 Currently automaps activates when you reach a specific zone. I suggest to run maps for equipment when it’s left a small amount of time until you will have enough resources for buying the last available metal upgrade. It will let to get much more resources from maps because you will have more books and maps level will be higher by the time when you will run the map. You will be able to buy equipment prestiges earlier which will lead to faster progress and better He/Hr. For high zones it will require a script which will calculate if higher level map will take more time (which is bad) and determine the best zone to run map. 
2.1 Currently autotrimps does not abandon soldiers and wait until they will be killed. It becomes a big problem, especially if you have a lot of HP (thousands times more than opponent’s damage). You rush through many zones with one group of trimps, you lose your overkill, progress slows by 2 times or even more. Furthermore game hires more and more geneticists to delay the breeding timer. I suggest to let timer to reach zero value when you need to run maps and to instantly abandon soldiers.
2.2 Sometimes in high zones if you can’t kill the Improbability fast Autotrimps start to run maps on cell 99. Isn’t it better to trigger farming at the start of the world’s zone in this case so you will be able to pass more cells with damage bonus?
3. Scrying formation. Currently I use the following configuration http://i.imgur.com/FPN3NZV.png
It allows me to use scrying for most of cells which I can overkill. But the problem is that if you will turn on scrying on maps there will be a great slow down on high zones (because S will be used even if you can’t pass the map as fast as with D), but if you don’t, there will be a slow down on low zones (because you will lose a lot of resourses and buy equipment upgrades slower). I suggest the following solution: 
a) if S overkills any cell with 100% chance – always use S
b) if D can’t overkill the cell but kills it with 1 hit with 100% chance AND S kills cell in 1 hit with 100% chance too – always use S.
4. Smarter void maps engine. Complete void maps which you have obtained after set void level if you can complete them without decreasing of your He/Hr.
5. Smarter engine for purchasing gigas which will be based on your damage and opponent’s HP relation.
Current system (where you set starting level and delta) is not flexible and precise, because the interval between zones where you obtain gigas is very different (starting from 2 on z60 and ending 10 on z180). New system will determine when it is better to buy giga automatically and much more precisely. Settings for other housing buildings are also superfluous. Why not to let system decide which building currently gives the best amount of trimps per building cost? System can make it much more efficient than human. (Of course warpstations still should have the highest priority because you can prestige them).

**Comment by genbtc** [comment]
You put a lot of time into this and I cant agree with these, there is not enough information to diagnose these problems you are having, and the "#2.0,#4,#5 are easier said than coded, and likely never going to happen. [Start using the genBTC branch please. ](https://github.com/genbtc/AutoTrimps/raw/gh-pages/.user.js)#2.1 should be fixed in it, and #2.2 should be fixed and it sounds like you were doing the Nom challenge where there is an option to either enable ot disable that. #3 there is a different code being used for scryer in the genBTC branch which does this.  Next time i'm feeling adventurous i will come back and read this and attempt to come up with a plan to implement your "smart engines". But Its near impossible to determine things that have time as an important variable. (the script cannot see into the future like run simulations of 9000 chess moves ahead.)
After youve tried the new script and figured it out, [come into the discord chat](https://discord.gg/upJpVvf) to have a back and forth about suggestions
daily challenges are the only really relevant thing imo, and the main task will be to make sure it doesn't get stuck during some of the modifiers, and also know when to portal

**Comment by genbtc** [comment]
Also, #5 the system already does calculate  "which building currently gives the best amount of trimps per building cost", the settings are only there to put a cap on them. The only ones that matter are Collectors and warpstations (unless you are lower level). Huts/Houses are independent, and Mansion/Hotel/Resort/Gateway/Wormhole/Collector are all tied together for Cost efficiency.
There is no way to determine a plan for gigas in advance. the best idea someone had was that the Giga Settings should auto-tune themselves by +1/-1 every time you portal based on how many coords you had left on the last zone. This is what matters, not your damage/HP at zone 60-180. You can look at the Graphs section for why.
