### ISSUE TITLE
Auto Magmite Purchase Revision

### ISSUE THREAD

**Issue by Jonathonathon** [zininzinin/AutoTrimps#209]
Hey genbtc.  There's been some work done on the most efficient spends for magmite so I was hoping you could adapt the script to account for these.  Reddit thread here:  https://www.reddit.com/r/Trimps/comments/5ebsjm/dimensional_generator_effective_ratios/

So my proposal is to purchase Capacity when it drops below a third of Efficiency.  For Supply, how about purchasing it when it is cheaper than Capacity?  Hopefully a simple algorithm that makes magmite more efficient for idle players.  Thanks!

**Comment by genbtc** [comment]
Working on it.

**Comment by genbtc** [comment]
Its done: [heres the code] (https://github.com/genbtc/AutoTrimps/commit/316d309764af431e3bcbcbb384d1d291ee0d9074#diff-4fa213adcbba66ebd78d1f437697c4da)
It uses the exact math, just not a general 3:1 (but that is a good generalization/approximation).
 +            //(try to) Buy Efficiency if its cheaper than Capacity in terms of Magmite cost per 
 +            //if not, (try to) Buy Capacity if its cheaper than the cost of Supply.
 +            //if not, (try to) Buy Supply.

This has raised a new concern, as to whether delaying the purchase of affordable efficiency upgrades (which is what it results in) with the 20% magmite decay on portal (maybe even 30% if you didnt buy the permupgrade)  will mean you are wasting a good portion instead of buying the thing ahead of time. I have a future plan to add code to account for this 20% loss.

**Comment by Jonathonathon** [comment]
That's a fair point, but for now this was exactly what I was looking for.  I'll go ahead and close this issue.
