### ISSUE TITLE
Rewrite of map logic

### ISSUE THREAD

**Issue by WG-SpaceCoder** [zininzinin/AutoTrimps#22]
This really really needs improvement. If anyone has any ideas please note them below!

**Comment by weltvagabund** [comment]
I can give you an algorithm, if that helps, but I cant code :) Give me a day to cook something up

**Comment by WG-SpaceCoder** [comment]
Yeah just a general
if this do that
if this do that

**Comment by weltvagabund** [comment]
Ok First off a general List of Motivations, why we map:
1. Prestige Updates from Equipment/Housing
2. Unique Unlocks
3. Map Completion Bonus 
4. Resources
For each of these there is a different Set of Rules, when to do this and what Prequisits have to be made. Currently I do not consider case 4. 

Here are the Basic dropping rules for Equipment:
On all Levels with 6 and 1 at the End (6, 11, 16, 21, ....) there is a new Shield, Dagger, Boots
On all Levels with 7 and 2 at the End there is Mace, Helmet
On all Levels with 8 and 3 at the End there is Polearm, Pants
On all Levels with 9 and 4 at the End there is Battleaxe, Shouldergards
On all Levels with (1)0 and 5 at the End there is Greatsword, Breastplate, Arbalest_, Gambeson_

On a Run there are 2(3) Phases: Climb, Run, (Deep Run)
For Climb it is preferd to go as quickly as possible. Therefore People with a lot of Helium go Map once every 10 Levels or do a Dagger/Mace or just a Dagger climb. It is a little dependent on playstyle.  After that there comes a run Phase, were you continue going for some extra Levels, due to Up to Date Equipment and Coordinations. After that comes the Deep Run Phase, were you take a long time to complete each level. (For me that is currently up to 59 Climb / Run till 95 / Deep Run after)

```

Suggested Options:
Unique Maps (Select which shall be hit)
    The Block (only interesting up to World 30 Runs)
    The Wall (+100% Resources)
    Dimension of Anger(Portal)
    Trimple of Doom(Challanges)
    The Prison(Electricity+other Challanges)
    Bionic Wonderland(Challanges)
Fast Climb: Dagger / Dagger & Mace / off
Time until World is considered Deep Run (10 Minutes) 
Run Maps for Housing unlocks y/n // I dont even bother to specifically unlock these anymore, they just happen, when I get Equip.


World 1 to 59 (after World 59 Enemy Damage Calculation Rules Change and Depend also on Formation)

Check Number of Missing Equipment Upgrades
If Weapon Damage > Enemy Life on Cell 99 set Climb Phase for World(n)
If FastEnemyMax Damage on cell 99 < Block+HP set Climb Phase for World (n)
// This allows to Oneshot every Enemy of the world, except for the Blimp/Impropability, where it is ok, if you die.
else
Run Phase for World(n)
//RunPhase will always catch up 4-6 missing Items per World from the Climb Phase. I can see that it will alternate a little between Run and Climb, due to the Extra Weapons coming in. But that is ok.

If World longer then 10(Settings) Minutes set to Deep Run

Run Map 1 time if Uniques/Unlocks option is Set to Y
Unlocks / Uniques
Run Map 8 for Mansion
Run Map 14 for Hotel
Run Map 18 for Uberhut
Run Map 23 for Nursery
Run Map 25 for Mansion
Run Map 29 for UberHouse
Run Map 30 for Gateway
Run Map 34 for UberMansion
(Run Map 37 for Wormhole)
Run Map 40 for UberHotel
Run Map 47 for UberResort
Run Map 50 for Collector

Run Map 12 for The Block
Run Map 15 for The Wall
Run Map 20 for Dimension of Anger (I prefer to run it just before I portal)
Run Map 33 for Trimpel of Doom
Run Map 80 for Prison
Run Map 125 for Bionic Wonderland
If Unique Map did not Run, and is checked in Options Run 1 Time


// Mapping algorithms

Dagger/Mace Fast Climb: (Climb Phase)
Check if Equip is missing
Run Maps with Equip First Setting
Run Map only if World ends with 6 and 1
Run Map 2/4 Times (2 Dagger / 4 Dagger&Mace)
Go back and run World

All Equipment: (Run Phase)
If you want to have all Equipment it is wise to run a Map (11/13) times every 5 Worlds. But this is not optimal, because you loose Map Bonus. Therefore it is more Optimal to run a map every two Worlds
Check if Equip is missing
Run Maps with Tier first
Run Map if World ends with 6,8,0,2,4
Run map 4/5/6 times until no Equip is missing (Max 10 Times)
Go back and run World

All Equipment NOW: (Deep Run)
Check if Equipment is missing
Run Map every World
Run map 10 Times (for the Map Bonus)
Go back and run World

```

Currently this only goes up to 59. I need to think more over the Conditions of Climb and Run for after 59. And if anybody has Feedback to the Conditions please share.

**Comment by weltvagabund** [comment]
I like the Idea behind the Parameters from /u/boxsalesman a lot. I did not see them before writing above. But if we combine them that would be pretty awesome:

Average time to kill a cell, calculated over the last 10 cells killed.

User defined : if it takes more than x seconds to kill a cell ( average of the last 10 cells ), it should go to maps instead.

The megablimp at the end of the zone should counts as 3 cells or something though as it's much slower to die than the others.

Just make sure the following doesn't happen =>

User selects 10 seconds

cell 1 killed in 8 seconds => ok, continues

cell 2 takes another 8 seconds, but after 2 seconds the script notices it going over 10 seconds and stops.

I think a good fix would be to always include +1 cell in the average calculation.

For example : you're killing the first cell, it has a counter of +1.

So whenever you take more than 10 seconds for that first cell, it'll boot you out.

When on the second cell, it'll have a counter of 2, so as long as you kill the second one before 20 seconds it'll keep you going. If at one point the time to kill cell 2 exceeds 20 seconds, it'll boot you to a map intead.

Mega blimps should count for 30 seconds as they're the big bad guy taking longer to kill.

**Comment by Ishakaru** [comment]
This is the basics behind running averages: You have the total summed times and divide that by the number of items that sum equals.  The reasoning behind the abstraction is because of start times.  So for the first 5 fights, we divide the time by 5 to get our decision value. Only after 10 times do we divide by 10. The issue with basing off time is how do we know when we can leave maps? 

As far as running maps for unlocks, I was thinking we would have a simple interface where we let the player select what they run for. A simple toggle for running maps when housing upgrades are available. Equipment gets complicated. If the tier first option in settings is active, then...idk...Give the option to run for gear at each level or stuck. If equipment first selected, then a drop down box(safest option) to dictate what level of gear to run up to. A clear indication is needed to let the player know what needs to be done in order to activate which set of options they are presented. Either that or have the options themselves set the game settings to make things work correctly. 

If the player selects to only get shield+dagger, they will eventually get stuck and end up getting all helmets, then all maces, so on and so forth. The various stages of game play(climb/run/deep run) will happen naturally with the correct stuck logic in place. 

As far as unique maps, give a toggle for each map. We need some way to determine if the map is beatable(within reason), or a setting for the player to determine number of zones after the map is available to run the map.

**Comment by weltvagabund** [comment]
Unlocking Housing/Nursey as dedicated Extras is a simple Yes No decision. 
Same with Unique Maps Y/N for each one. There is a canbeatlastcell() that @spindrjr is working on. That should be able to determine if a unique is beatable.
A moving average of 5 or 10 Fights is a great Idea. We should just exclude the Boss of each World, because these could glitch everything.  With this timing we could define a "fast" time, a "normal" time and a "Deep run" time. We should also check if the Boss is beatable and a Snimp in Cell 99. Else it is better to run a Map asap for the extra Attack and more Equipment.
For Equip Only or Tier only, this should be set automatic by the script, depending on the Strategy. Setting this manually is way to error prone
The drop down for the Shield/Dagger/mace etc. is a brilliant idea.

**Comment by HyperWeapon** [comment]
First off auto map works great pre-zone 60. No complaints. However progression afterwards is somewhat slow near the end of a run still. 
It appears that it will exit the map and attempt to progress only if your gear allows your Trimps to one-shot the majority of enemies in the current world zone,(If I'm reading the code right until you can deal 84% of a Grimp's HP in one hit), this value ignores the map bonus. The Mega Books found in each world zone are extremely powerful for progression. It is better to move on just for for them if you have reasonable damage and health.
Right now I believe including current map bonus in this calculation would help late game progression.

**Comment by weltvagabund** [comment]
Current Suggestions for the Automapping:
It runs fine for me up to 120, but as HyperWeapon describes it gets stuck there. Therefore I suggest some additions to the algorithm:
1. Let a Map run a Maximum of 10 Times. Then continue with the World
2. Only run a Map in the first Row of  the World. I find it less effective if I spend 10 Maps on the second last cell of the World. It wastes the 200% Map Bonus
3. If a world is hardly beatable (Criteria Snimps Maxdamage 80% Health and Block / Own Damage less then 10% GrimpHealth) and there are Prestige Upgrades left, go farming on a metal map. If there are no Prestige upgrades are left goto 1.

**Comment by spindrjr** [comment]
@HyperWeapon just for reference the calculation is actually based off of if we can 1-shot an 84% health grimp at the end of a map with titimp up in the next zone. The basic idea is to keep our map farming speed top-notch to maximize resource gain in them.

@weltvagabund your #2 can cause a good bit of interference with stuff like breed timer. In any zone where we are relying on the map bonus to clear, it shouldn't really matter. If it's wanting to map when it enters a zone and doesn't do so until late in the map, you already have a really strong army and it's of little consequence. That has been my experience with it. Have you seen otherwise?

As both of you have noted, once we are nearing the end of a 'general' (eg. not stretching our limits to hit a goal) run, it basically hits a wall due to not using map bonus. I think just throwing in 10 map bonus = move on would be quite effective, but we need a couple of conditions to check for when to move in and out of this.

Snimps hitting for 80% of our EHP seems way too far to me. Assuming we are using a 30s timer, if we hit that point we have probably been wasting tons of time in heap and waiting for new armies. In my last run I ran out of steam at about 120 and started manually moving with 10 map bonus. After around 11-12 zones it seemed to be hitting a wall for that method, with having to drop into nostance in maps and heap in the world, which is sort of when I consider things ineffective. At that point a snimp at around cell 80 I could 2-shot in dominance with full map bonus. I was thinking maybe make the first condition something like if we can't 1 to 1.5-shot a Snimp at cell 30 with full map bonus, we need to farm.

As far as when we decide to hop out of farming a map I would probably just put it on the lower end of the condition to move in to farming. So for example, if we can't 1.5-shot Snimp, go to farming. If we farm enough to 1-shot snimp (+~50% damage?), move back to progression.

Let me know if you guys have any opinions/alternate ideas. Maybe if you are at the end of a run see if feel the same about when it starts to slow down after starting map bonus pushing or see roughly what a snimp's HP is compared to your full map bonus dominance hit (and about what cell, Hp scales with higher cell).

**Comment by foopex** [comment]
My current run has been absolutely destroying this map for 13 hours now, script was current as of then.
http://puu.sh/mC7kx/f9537a8a1b.png
http://puu.sh/mC85g/5e37d7a9fa.png
Settings:
http://puu.sh/mC7oP/43aa66d81b.png
Export:
http://pastebin.ubuntu.com/14578670/

**Comment by spindrjr** [comment]
@foopex this is actually caused because the player's damage is updated by the autostance function in the live build. This means with autostance off, it is never updating your damage. I actually fixed this in my current build already but for now just turn autostance on.

**Comment by HyperWeapon** [comment]
Another idea for the offensive check on when it's ok to progress to try to fix that end of run slowness. Just a method to consider.
If max rank Relentlessnes and in zone 60+ check if a crit will be enough damage for the current offensive check. If that doesn't workout then halve the current offensive.check so for.certain every other hit will kill if not the first.
My thoughts are if the player on average halves their mapping speed since half the hits should be 1-shots then for 50% or 60% more loot progressing is worth it since the base loot has increased and to a lesser extent, new prestige upgrades are unlocked.
Of.course the player would still need to pass the defensive check to progress as dropping out of Dominance is always a bad idea.

**Comment by spindrjr** [comment]
I just pushed an update with some map bonus pushing. It automatically moves back to the world if it hits max map stacks to start pushing with map stacks, and once this starts to slow down it effectively switches to a different farming logic.

It seems to work quite well at my helium levels (8-9M) but of course I chose the ratio based on that. I would be interested to hear if people find it switching to 'farm' maps (denoted by it staying in maps farming past 10 map bonus, or you can type shouldFarm in console to see the status) too early or too late and what your helium level is. 

The overall goal is to not push too far such that map farming is slow. On my setup, upon entering a new zone where we were having to 'farm' the previous zone, it of course wants to farm again immediately due to the new mob scaling. It will push through past megafarming before sitting to map. The map farming is a little bit slow upon first starting this, slightly less than a true 1-shot farming with titimp up. Moving to the next zone in this case would be a bit too much IMO. Let me know how it goes for you guys.

**Comment by weltvagabund** [comment]
I looked at it yesterday and it ran up fine to about 117. Thereafter I deactivated AutoMap and it continued up to 127 without Problems. It was almost one Shot farming, as you described it. 
What would be really helpfull would be some console entries for following Things happening:
Switch to Farm Mode
Switch to Map (and why: Prestige/Ressource)
Switch to World
Then you could actually see, how long the Script farms each Map, without sitting next to it.

**Comment by spindrjr** [comment]
Are you saying the latest version hit a wall at 117 and turning it off moved you up to 127 fine? If so can you give me an export at the wall on your next run?

**Comment by weltvagabund** [comment]
Well it went slow for my feel. I am currently running 8 to 15 hrs Electricity runs. I am gearing up for a Nom run soon. I just want to get Coordination and Carpentry up a little more. So when I feel its going slow, I disable AutoMap, and let it run for about another 2-3hrs before I portal. I consider this the"End Game" where I stop getting too much Equipment or Gigastations. It is just to take some extra Helium before I Portal. Latest tomorrow morning i can attach you a save.

**Comment by spindrjr** [comment]
Ah ok. That's completely different from what I was thinking. I can look into the console messages to see if there is a good spot for them.
