### ISSUE TITLE
AutoTrimps v2 No longer uses "Max hits to kill enemy before stuck"

### ISSUE THREAD

**Issue by PatrickDattilio** [zininzinin/AutoTrimps#28]
Seems some code was lost along the way?

**Comment by spindrjr** [comment]
The UI is in a temporary state as a large overhaul of it is due soon. I just pushed an update that should enable the buildings max entries to be usable, but some other things you will find won't work (including max hits entry) and some new functionalities don't have options yet and are hardcoded as we wait for the UI overhaul. Keep in mind all of V2 is still very beta (we haven't even officially released it) so export your save regularly and create an issue for any bugs you find or suggestions you have.

That being said, the automaps logic is a brand new routine from @Belaith that should function much better even without options to it. It easily climbs me above 100 without intervention. Try it out and let us know if you have any issues or suggestions for it.

I'll leave this issue open in case other come here wondering about it.

**Comment by Ishakaru** [comment]
Work got in the way yesterday. I have most of the new UI done. I've got some tweaking left to do to make it pretty. Then I'm going to have to hand it off to you guys to alter your bits and pieces to take data from the new stuff rather than the old stuff. I'll try to have my part finished tonight before I go to bed. Worst case... Wednesday. 

This is assuming I can wrap my head around Git. First time I've used it.

**Comment by spindrjr** [comment]
Yea if you can just get a case working for each of a value and a toggle button, I should be able to take it from there.

**Comment by Ishakaru** [comment]
https://raw.githubusercontent.com/Ishakaru/AutoTrimps/master/UI%20work

@spindrjr copa pasta This.

buildAutoSettings() at the very bottom of the code. The first for-loop demo's the button, the second demo's the value input. (it's not suppose to be a value input, but w/e it is because we say it is! TAKE THAT! =-P ) I've put the comment somewhere in the code... but I'll put here for emphasis. The load should happen after the injection, but before that function. Don't load items out of order of index unless you first put in code to take care of "undefined" values in the array(should be done right after the array size check)... ment to put that in there >.>

Practically everything else is the same, cept the bug fix and some other things.

**Comment by spindrjr** [comment]
This looks great man, thanks. In actually considering how I was going to add this to the script, I've decided it is beyond my abilities. So I'll have to wait until @zininzinin has time to do it :/

**Comment by Ishakaru** [comment]
Okie, wrapped things up to be user friendly. With instructions on what where.

**Comment by spindrjr** [comment]
v2 interface is live, closing.
