### ISSUE TITLE
Unlimited nurseries slow down warpstations too much

### ISSUE THREAD

**Issue by spindrjr** [zininzinin/AutoTrimps#29]
From weltvagabund:
But I noticed one thing with the Auto Buy Nurseries, that is still present in the current version. High Level Nurseries consume a LOT of Gems. So they significantly delay the buying of new Warp/Gigastations, if left run to the maximum. (buy one Warp, buy Nursery, buy Nursery, buy Nursery, buy Warp, ...) With waiting times of 5 to 15 min, this really puts a dent in Coordiantion Updates. Maybe we should insert a Cost Break in somewhere, as of use max 25% of Gem Production, or if Gem Storage > Highest Warpstation ever bought *2.

I am not sure how to define the Breakpoint now, but for the sake of fast progress i always prefer Trimps over Nurseries.

**Comment by Ishakaru** [comment]
I was thinking about something close to this. I was more concerned about gyms. 80% reduction in zones is significant for keeping your trimps alive.

So if I was to write something to manage this, I would go with just focusing on keeping block(gyms) just above 160%(to account for being in dom or heap stance) of the expected damage for the next zone. This in turn would lessen the number of nurseries, and increase the number of warp/giga's. This would have a cyclic effect in where the population would rise, increasing the number of cordinates feeding into a higher block than needed reducing the number of gyms needed feeding into nurseries being purchased more. But the base survivability stat is maintained first with an emphasis on speed:more time in D+X than H... I think? I personaly don't like H. I'll check the stance dance function to make sure that it leaves H when a new group of combat trimps is ready, because I feel it's a waste of time.(maby an option)

**Comment by spindrjr** [comment]
Unlimited nurseries should now only be purchased if they are less than 5% of current warpstation cost.
