### ISSUE TITLE
Buying population related buildings

### ISSUE THREAD

**Issue by fayumot** [zininzinin/AutoTrimps#57]
There seems to be a point after you unlock the collector wherein the script just stops buying population related buildings and wait until it can buy warpstations. This is more apparent with collectors since it doesn't buy any collectors at all up until it bought warpstations.

**Comment by spindrjr** [comment]
Are you using v2 of the script? It sounds like yours is not buying any collectors until after it has bought some warpstations? Can you check to see that your settings don't have collectors capped?

I just watched mine this run and it seemed to work as expected. As soon as collector was unlocked, it started buying them. It continued buying them after warpstations are unlocked until they are around half the cost in gems as a warpstation, at which point it will buy the first warpstation and alternate between them for a while.

An export of your game along with a picture of your automation settings would be helpful if you continue to have this problem.

**Comment by fayumot** [comment]
Yes this is the v2 of the script on firefox and yes i have collectors capped to 100.

Settings
![capture](https://cloud.githubusercontent.com/assets/8320680/12529781/b751fda0-c1ff-11e5-837f-5f89544b96b6.JPG)
Export
[trimps.txt](https://github.com/zininzinin/AutoTrimps/files/101814/trimps.txt)

**Comment by spindrjr** [comment]
Cap your gateways much lower. It wants to buy gateways because they are cheaper when just considering gems. I have mine capped at 20, they should default to 25 these days but if you upgraded to v2 early it might have been set higher. I can see if there is a good way to make an exception for gateways in the code.

**Comment by fayumot** [comment]
Lowering the cap on gateway to 25 seems to work around it. It would be nice to have a fix though. Thanks for the help and keep up the good work!

**Comment by mdmdj** [comment]
This issues I have with this as it works now is that a lot of time seems wasted waiting for fragments to build Gateways when the lower level buildings could be built right away and leave plenty of time to gather the resources again to build the next Gateway by the time the fragments are ready.

Secondly, building Nurseries constantly sucks away the gems needed for the Collector, so you can get into a situation where you won't have enough gems for a Collector for a long long time unless you make a bunch of tweaks around the time Collectors get unlocked. This is also happening at times when more Nurseries are not helping me progress.

Maybe the way the priority is handled within the population buildings can be tweaked , and the balance between Collectors and Nurseries can also between.

At least this has been my experience so far in the 15-23k helium range. Seems quite a ways away from getting Warpstation and Gigastation.

I don't have math to support this though, just perception.

**Comment by mdmdj** [comment]
It seems that Nurseries get built even when BuildNurseries is disabled but ManageBreedtimer is enabled.

I think this might be due to the block at the end of the manageGenes function under the comment "//really should be integrated with the buyBuildings routine instead of here, but I think it's mostly harmless here" because it doesn't check BuildNurseries before building nurseries. 

If this is by design, maybe the settings page can clarify the behavior or force the states of BuildNurseries and ManageBreedtimer to be consistent with each other.

This would exacerbate the Collector issue because of the gems being used. For those of us that haven't reached the point where Geneticists are in play it's very confusing.

I know this is a bit of a tangent but I wasn't sure if you'd want a new issue for this or not.

**Comment by spindrjr** [comment]
The nursery thing was not by design. I'll fix it. As for the original gateway issue, in my next build the logic will not consider purchasing gateways if they can't be bought right now. This should hopefully allow fragments to build up for purchase without stalling collectors.

**Comment by spindrjr** [comment]
The latest version should have this resolved.
