### ISSUE TITLE
Consider Siphonology perk

### ISSUE THREAD

**Issue by PatrickDattilio** [zininzinin/AutoTrimps#60]
Calculate map level using the level of the Siphonology perk for faster map bonus farming.

**Comment by Ishakaru** [comment]
As the logic is set up now, the current map is farmed until there is enough attack(+/-) to one shot every thing in a map one level higher. This was done because we run maps mostly for resources at the push stage of the game. The map bonus... isn't why we are ever there, and the speed is as fast as it's going to get.

**Comment by HyperWeapon** [comment]
Back before Crushed existed the gap in he/hr increase from Electricity and Nom was huge and made using Siphonology slightly worth it near the end of a Nom run. Now with Crushed however this strategy is a waste of time, and one is better off blitzing Crushed runs until they can blitz Nom.
