### ISSUE TITLE
[Feature] Strategy for Crushed and Toxic Runs

### ISSUE THREAD

**Issue by weltvagabund** [zininzinin/AutoTrimps#61]
Lets define a subset of optimal Parameters for a Crushed and Toxicity Runs (Stances/Worker Distributuion/Leveling&Maps). Conditions see here:
http://trimps.wikia.com/wiki/Crushed
http://trimps.wikia.com/wiki/Toxicity

**Comment by Ishakaru** [comment]
For crushed, I don't see any special rules needed. Keeping block that high isn't feasible. Once you hit 70 and geneticists are unlocked your hp is going to sky rocket, and will continue to do so. This is needed more for the anticipation perk than the actual health imo. To keep the block that high you would need to farm wood maps while changing the ratio for wood to be => metal. This in turn slows down the run, because you have less metal for upgrades. So you end up needing to spend that much more time farming the metal maps for the Attack/HP you need to progress. This is opposed to roughly 300% increase(x3) damage from the imps on average. Sometimes it'll spend some extra time on breeding, but not nearly as much time we would be spending on farming wood/metal.

Now for toxicity... my first thought is that you don't need any special rules there either... since geneticists are auto purchased and fired on need. This is more of an account capability thing. Need a high level of pheromones, enough to fully counter the effects of the stacks. Not something within the control of the script atm.

**Comment by weltvagabund** [comment]
I will start a crushed run tonight. Lets see how the Script behaves.... I am thinking that the Stance Dance needs to be modified most. It should take the extra Damage into account and maybe should go Domination, Standard, Barrier, instead of Heap. 
So far I cant speak for toxicity, i need to get more helium under my belt to get there....

**Comment by spindrjr** [comment]
I did one run of Crushed just to check out the He/Hr vs. Nom. The graph of the progress looked completely normal. My total helium is already well into nom range but I doubt any changes really need to be made for it. Since trainers are already bought as can be afforded with tribute, block is generally very high throughout. The few times I looked at it the army was chugging away after being crit down to whatever health level their block was at.

Toxicity I will definitely work on when I start trying to run it. I'm hoping we will be able to just let it run under nom settings and have the timer automatically handled, as we shouldn't be stacking too high at appropriate helium levels. Though I imagine some tweaking or checks will need to be added in the 70s range to control hiring/firing of geneticists which can get a little stuck eating 100% of food when the timer is changing.

**Comment by uefigs139** [comment]
I have a little over 4 million helium. If I get hit back to back to back with a critical hit when running Crushed, the Auto Stance cannot keep up, causing me to die before my next set of trimps is ready to attack.

**Comment by cejaann** [comment]
I have been running toxicity today but sadly had to do it without the script as it totally seems to break. It won't let me control the breed timer. It tries to keep it at 30.5 seconds but even with manage breed timer disabled it buys geneticists like crazy. I was over 600 seconds breed time when I gave up and shut the script off. I tried firing geneticists and it would instantly rehire them. I don't think it's taking into account my stacks.

**Comment by weltvagabund** [comment]
Well the Script did not learn yet how to handle these challenges, welcome to the frontier :)
Ok here the things, which should be modified for crushed. I think with these Parameters we will have a smooth ride for crushed:
- Needs to Auto Run Bionic Wonderland
- Autostance needs to Shift from Dominance, Normal, Heap to Dominance, Barrier at Level 70
- Autostance needs to take the extra Damage into Account (+400%) The only longer downtimes I encountered were Snimp Hits at the end of Dominance which killed me

**Comment by HyperWeapon** [comment]
Did a couple runs of Crushed. Aside from not running Bionic wonderland and Autostance considering getting crit it works fine as is. No need to adjust for Barrier or anything.
As long as the player puts some points into health as they should the challenge adds only a bit of time.

**Comment by weltvagabund** [comment]
After running the Crushed several times now, i have to agree, the only thing to do is to adjust the Damage Calculation and the Auto Run Bionic 1

**Comment by spindrjr** [comment]
Though it is 100% untested (but I'm pretty sure it runs?), I updated the code on my branch to hopefully include:

-Breed timer that accounts for Toxicity stacks
-Automaps that runs Bionic Wonderland (with difficulty check similar to prison, it will probably run it 2-3 zones after 125)
-Stancedance that accounts for crushed crits and toxicity nom-effects (pretty sure toxicity attack and health changes should be picked up automatically from getting the cell attack and health, but let me know if they don't seem to be.)

Let me know if it works or doesn't if you try it out.

**Comment by HyperWeapon** [comment]
Let your branch do a run up to 140 Crushed run. Set it up to do a boot climb.
-StanceDance doesn't check for fast crushed crits. Only a minor inconvenience.
-Never ran Bionic Wonderland. 15 zones later and it didn't try. Manually had to do it.

**Comment by spindrjr** [comment]
Fixed something that probably caused the automap not to go off. Not sure about the stance dance. Still looks like it should to me. Is it critting you out of dominance, or nostance, or both?

**Comment by uefigs139** [comment]
What would be the bookmark link for your branch (if it is even possible)?

**Comment by spindrjr** [comment]
Same URL except where it usually says /master/AutoTrimps2 put
/spin/AutoTrimps2

**Comment by HyperWeapon** [comment]
@spindrjr Fast enemies can crit my army from low health to death in both None and Dominance. Only usually happens before a X6th or X1st zone, lets call these weak zones , where my health is the lowest before getting another boot upgrade. 
And this is only a small time loss, 10 or so seconds each bad death. Maybe once or twice each weak zone around zones 60 and low 70. Doing a Helmet climb would fix this while keeping roughly the same time, I believe.

**Comment by weltvagabund** [comment]
It feels like it is not properly switching (or be more precise not switching at all) between 60-70. The Fast Enemys Death Crit me a lot. As written a minor inconvenience (between 10 and 20 Sec loss), but should not happen.

**Comment by spindrjr** [comment]
K think I found it. Try refreshing.

**Comment by weltvagabund** [comment]
Seems to work....

**Comment by uefigs139** [comment]
Using spindrjr's fork. Things bogged down at 120. I would die long before the next batch of trimps was ready. The game was staying on the world. Had to manually switch to a map.

Update: I ran maps manually until everything was caught up, and I earned enough to upgrade everything to level 22. Once I did that I put it back on Auto, and things have run smooth since.

**Comment by spindrjr** [comment]
@uefigs139 had you already been advancing on map bonus for a while by then? If so, it might have been in farming mode, and wanting to get past megafarming upgrade before it sat down to farm. You can check this by typing shouldFarm into the console. If it's true, it wants to beat cell 80 before mapping.

**Comment by uefigs139** [comment]
Things progressed pretty smoothly until it got into those high 110s. Once it hit 120 it really slowed down, and I took over. It wasn't trying to go to maps, it seemed very happy to just sit at 120 and let me die and wait. I will check that out on my next run. I am pretty sure it stalled out before it got to the mega updates.

**Comment by spindrjr** [comment]
Think it's running these fine. Closing.
