### ISSUE TITLE
Void Maps Being Ignored

### ISSUE THREAD

**Issue by kevrlet** [zininzinin/AutoTrimps#87]
Just to test the system, I set the script to clear Void maps at zone 40. The script skips them entirely. This may be because at z40 I have to farm for over an hour to survive them, but you did mention it 'should' try to farm to beat them if told to run them.

**Comment by spindrjr** [comment]
Yea can you give me an export when you have it skipping it entirely?

**Comment by kevrlet** [comment]
Sure. I'll catch one tomorrow after I portal

**Comment by kevrlet** [comment]
[voidmapskip.txt](https://github.com/zininzinin/AutoTrimps/files/145141/voidmapskip.txt)

Saved on the last square of 39. Did 3 tests by re-importing this save. It doesn't even try to run normal maps here, despite Auto Map being enabled, so it might be some conflict with the Void code and the auto mapping code?

**Comment by spindrjr** [comment]
thanks i'll check it out.

**Comment by spindrjr** [comment]
In your case this could have been one of a couple of issues that should be fixed in the latest push. For starters, the difficulty check got different attack values based on when it was called. You happened to fall in a range that caused the logic to fall through and do no void maps.

Secondly, the difficulty check should now take into account balance stacks.

I think it's fixed so I'll go ahead and close this. Re-open if you find it happening again.
